name: Publish ebook to release

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "stable"
    paths:
      - ".github/workflows/build-ebook.yaml"
      - ".github/workflows/publish-release.yaml"
      - ".releaserc"
      - "src/**"
      - "theme/**"
      - "book.toml"
      - "package.json"
      - "pnpm-lock.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build-ebook.yaml

  publish:
      permissions:
        contents: write
      needs: build
      if: ${{ !(github.event_name == 'push' && contains(github.event.head_commit.message, '[skip release]')) }}
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Setup pnpm
          uses: pnpm/action-setup@v3
          with:
            version: latest
            run_install: true

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            cache: pnpm
            node-version: current

        - name: Download artifact
          uses: actions/download-artifact@v4
          with:
            name: ebook
            path: ebook

        - name: Release ebook
          env:
            GITHUB_TOKEN: ${{ github.token }}
          run: pnpm exec semantic-release
