name: "Update flake"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/update-flake.yaml"
  schedule:
    - cron: '31 2 * * 5'

permissions:
  contents: write

jobs:
  sync-flake:
    runs-on: ubuntu-latest
    environment: flake
    steps:
      - uses: DeterminateSystems/nix-installer-action@main

      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
          token:  ${{ secrets.PAT }}

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git show -s

      - name: Update flake
        run: |
          nix flake update --accept-flake-config
          nix flake info --accept-flake-config

      - name: Update flake
        run: |
          git add .
          git status
          git commit -m "dep: flake update $(date +'%Y-%m-%dT%H:%M:%S')" || exit 0
          git push
